app_key: "7pwoeu9lvwww12m"
app_secret: "9c7kce93e0d7kdm"
access_token: "QnUHs75QdVoAAAAAAAAHW6fs4dMulm37ACI2PMM52fz098HDx0ZUYZriPKlMH7PM"
access_token_secret: "..."
user_id: "..."
access_type: "dropbox|app_folder"